# Generated by Django 5.0 on 2026-02-15 16:28

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cafes', '0001_initial'),
        ('users', '0003_restaurantstaff'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('booking_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('booking_number', models.CharField(editable=False, max_length=20, unique=True)),
                ('booking_date', models.DateField()),
                ('booking_time', models.TimeField()),
                ('number_of_guests', models.IntegerField()),
                ('duration_minutes', models.IntegerField(default=120)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('seated', 'Seated'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('no_show', 'No Show')], default='pending', max_length=20)),
                ('special_request', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cancellation_reason', models.TextField(blank=True)),
                ('assigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_bookings', to='users.restaurantstaff')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='users.customer')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='cafes.location')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='cafes.restaurant')),
                ('table', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to='cafes.table')),
            ],
            options={
                'db_table': 'bookings',
                'ordering': ['-booking_date', '-booking_time'],
                'indexes': [models.Index(fields=['booking_date', 'booking_time'], name='bookings_booking_a7d490_idx'), models.Index(fields=['customer', 'status'], name='bookings_custome_b789e2_idx'), models.Index(fields=['location', 'booking_date'], name='bookings_locatio_c3c60e_idx'), models.Index(fields=['status'], name='bookings_status_51373b_idx')],
            },
        ),
    ]
