# Generated by Django 5.0 on 2026-03-04 15:18

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
        ('users', '0003_restaurantstaff'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookingComment',
            fields=[
                ('comment_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('comment', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_visible_to_customer', models.BooleanField(default=False)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='bookings.booking')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booking_comments', to='users.restaurantstaff')),
            ],
            options={
                'db_table': 'booking_comments',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['booking', 'created_at'], name='booking_com_booking_95bb0e_idx'), models.Index(fields=['staff', 'created_at'], name='booking_com_staff_i_451cbe_idx'), models.Index(fields=['is_visible_to_customer'], name='booking_com_is_visi_0773b1_idx')],
            },
        ),
    ]
