# Generated by Django 5.0 on 2026-02-08 16:31

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('restaurant_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='Restaurant ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название Ресторана')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('cuisine_type', models.CharField(help_text='Например: Итальянская, Казахская, Азиатская', max_length=100, verbose_name='Тип Кухни')),
                ('address', models.TextField(verbose_name='Основной Адрес')),
                ('city', models.CharField(default='Almaty', max_length=100)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Широта')),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Долгота')),
                ('images', models.JSONField(blank=True, default=list, help_text='Массив URL изображений', verbose_name='URLs Изображений')),
                ('rating', models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(5.0)], verbose_name='Средний Рейтинг')),
                ('total_reviews', models.IntegerField(default=0, verbose_name='Всего Отзывов')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлен')),
            ],
            options={
                'verbose_name': 'Ресторан',
                'verbose_name_plural': 'Рестораны',
                'db_table': 'restaurants',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['city', 'cuisine_type'], name='restaurants_city_043837_idx'), models.Index(fields=['-rating'], name='restaurants_rating_422bd4_idx'), models.Index(fields=['-created_at'], name='restaurants_created_af34c6_idx')],
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('location_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='Location ID')),
                ('address', models.TextField(verbose_name='Полный Адрес')),
                ('city', models.CharField(default='Almaty', max_length=100)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('opening_hours', models.CharField(help_text='Например: Пн-Пт 10:00-22:00, Сб-Вс 11:00-23:00', max_length=200, verbose_name='Часы Работы')),
                ('total_capacity', models.IntegerField(default=0, help_text='Рассчитывается автоматически из столиков', verbose_name='Общая Вместимость')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='cafes.restaurant', verbose_name='Ресторан')),
            ],
            options={
                'verbose_name': 'Локация',
                'verbose_name_plural': 'Локации',
                'db_table': 'locations',
                'ordering': ['restaurant', 'city'],
            },
        ),
        migrations.CreateModel(
            name='Table',
            fields=[
                ('table_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='Table ID')),
                ('table_number', models.CharField(help_text='Например: T1, A5, VIP-3', max_length=10, verbose_name='Номер Столика')),
                ('table_type', models.CharField(choices=[('indoor', 'Indoor'), ('outdoor', 'Outdoor'), ('vip', 'VIP'), ('terrace', 'Terrace'), ('bar', 'Bar Seating'), ('private', 'Private Room')], default='indoor', max_length=20, verbose_name='Тип Столика')),
                ('min_guests', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Минимум Гостей')),
                ('max_guests', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Максимум Гостей')),
                ('capacity', models.IntegerField(editable=False, verbose_name='Вместимость (устаревшее поле)')),
                ('position_x', models.IntegerField(blank=True, null=True, verbose_name='X Позиция на Плане')),
                ('position_y', models.IntegerField(blank=True, null=True, verbose_name='Y Позиция на Плане')),
                ('description', models.TextField(blank=True, help_text='Особенности, вид и т.д.', verbose_name='Описание')),
                ('is_available', models.BooleanField(default=True, verbose_name='Сейчас Доступен')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен (не на ремонте)')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tables', to='cafes.location', verbose_name='Локация')),
            ],
            options={
                'verbose_name': 'Столик',
                'verbose_name_plural': 'Столики',
                'db_table': 'tables',
                'ordering': ['location', 'table_number'],
            },
        ),
        migrations.CreateModel(
            name='TimeSlot',
            fields=[
                ('time_slot_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='TimeSlot ID')),
                ('start_time', models.TimeField(verbose_name='Время Начала')),
                ('end_time', models.TimeField(verbose_name='Время Окончания')),
                ('duration', models.CharField(help_text='Например: "2 часа", "90 минут"', max_length=50, verbose_name='Длительность')),
                ('days_of_week', models.JSONField(default=list, help_text='Список названий дней: ["Monday", "Tuesday", ...]', verbose_name='Активные Дни')),
                ('max_bookings', models.IntegerField(default=10, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Максимум Бронирований на Слот')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_slots', to='cafes.location', verbose_name='Локация')),
            ],
            options={
                'verbose_name': 'Временной Слот',
                'verbose_name_plural': 'Временные Слоты',
                'db_table': 'time_slots',
                'ordering': ['location', 'start_time'],
            },
        ),
        migrations.AddIndex(
            model_name='location',
            index=models.Index(fields=['restaurant', 'is_active'], name='locations_restaur_25b3aa_idx'),
        ),
        migrations.AddIndex(
            model_name='location',
            index=models.Index(fields=['city'], name='locations_city_278550_idx'),
        ),
        migrations.AddIndex(
            model_name='table',
            index=models.Index(fields=['location', 'is_active', 'is_available'], name='tables_locatio_03c116_idx'),
        ),
        migrations.AddIndex(
            model_name='table',
            index=models.Index(fields=['table_type'], name='tables_table_t_3a7893_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='table',
            unique_together={('location', 'table_number')},
        ),
        migrations.AddIndex(
            model_name='timeslot',
            index=models.Index(fields=['location', 'is_active'], name='time_slots_locatio_f38e8e_idx'),
        ),
    ]
