# Generated by Django 5.0 on 2026-04-07 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='table',
            name='height',
            field=models.IntegerField(blank=True, null=True, verbose_name='Высота на Плане'),
        ),
        migrations.AddField(
            model_name='table',
            name='radius',
            field=models.IntegerField(blank=True, null=True, verbose_name='Радиус (для круглых)'),
        ),
        migrations.AddField(
            model_name='table',
            name='rotation',
            field=models.IntegerField(default=0, verbose_name='Поворот (градусы)'),
        ),
        migrations.AddField(
            model_name='table',
            name='shape',
            field=models.CharField(choices=[('rect', 'Rectangle'), ('round', 'Round')], default='rect', max_length=10, verbose_name='Форма на Плане'),
        ),
        migrations.AddField(
            model_name='table',
            name='width',
            field=models.IntegerField(blank=True, null=True, verbose_name='Ширина на Плане'),
        ),
    ]
