# Generated by Django 5.0 on 2026-04-07 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafes', '0002_table_height_table_radius_table_rotation_table_shape_and_more'),
        ('users', '0003_restaurantstaff'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurantstaff',
            name='restaurants',
            field=models.ManyToManyField(blank=True, help_text='Рестораны, которыми управляет/к которым имеет доступ сотрудник', related_name='staff_members', to='cafes.restaurant'),
        ),
    ]
