# Generated by Django 5.0 on 2026-03-04 15:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafes', '0001_initial'),
        ('users', '0003_restaurantstaff'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurantstaff',
            name='hire_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='restaurantstaff',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='restaurantstaff',
            name='position',
            field=models.CharField(choices=[('waiter', 'Waiter'), ('manager', 'Manager'), ('host', 'Host'), ('chef', 'Chef')], default='waiter', max_length=50),
        ),
        migrations.AddField(
            model_name='restaurantstaff',
            name='restaurant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='staff', to='cafes.restaurant'),
        ),
    ]
